# Generated by Django 4.2.7 on 2023-12-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='Entreprise')),
                ('siret', models.CharField(blank=True, max_length=14, null=True, verbose_name='SIRET')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Tél')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Télégram')),
                ('address', models.CharField(max_length=100, verbose_name='Adresse')),
                ('city', models.CharField(max_length=50, verbose_name='Ville')),
                ('zip_code', models.CharField(max_length=10, verbose_name='CP')),
                ('country', models.CharField(default='France', max_length=50, verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
            },
        ),
    ]
